services:
  - type: web
    name: hrms-lite-api
    env: docker
    plan: free
    # This file lives inside the `backend/` folder,
    # so the Dockerfile path should be relative to that.
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: hrms_lite
      - key: CORS_ORIGINS
        sync: false

